name: Code quality tests

python-code-for-main: &python-code-for-main
  branches:
    - main
  paths:
    - "pyproject.toml"
    - ".github/workflows/style-lint-and-test.yml"
    - "**.lock"
    - "Makefile"
    - "**.py"
    - "**.pyi"
    - "**.scss"

on:
  push:
    <<: *python-code-for-main
  pull_request:
    <<: *python-code-for-main

jobs:

  style-lint-and-test:

    name: Style, lint, test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rye
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"

      - name: Install Dependencies
        run: make setup

      - name: Check the Code style
        run: make codestyle

      - name: Lint the code
        run: make lint

      - name: Type check the code
        run: make stricttypecheck

      - name: Run unit tests
        run: make test

### style-lint-and-test.yaml ends here
